title: 'Mashup Template'
tagline: 'Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor.'
author:
  name: Hugh Barnes
  # email: 'joe@test.com'
metadata:
    description: 'Demo of port of Savory theme to Grav content management system. "Mashup templates have been developped by Orson.io team."'
    rights: © Untitled

globals:

  contacts:
    email: e-mail@mail.io
    phone:
      country: 33
      region: 09 07
      number: 45 12 65
    address: '42 rue Moulbert 75016 Paris' # optional in template

  social: # these names are added to make the social links show
    facebook: vacuousExample
    twitter: realDonaldExample
    instagram: selfieExample
    dribbble: drabExample
    linkedin: porfesionalExample
    # pinterest: iamPinterested
